"""empty message

Revision ID: 6140e02841a1
Revises: 573ff1c1f939
Create Date: 2022-05-26 15:40:14.600613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6140e02841a1'
down_revision = '573ff1c1f939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('animal', sa.Column('price', sa.Float(precision=2), nullable=False))
    op.add_column('animal', sa.Column('image', sa.String(length=100), nullable=True))
    op.add_column('animal', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.drop_column('animal', 'cool')
    op.drop_column('animal', 'created')
    op.add_column('user', sa.Column('api_token', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'api_token')
    op.add_column('animal', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('animal', sa.Column('cool', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('animal', 'created_on')
    op.drop_column('animal', 'image')
    op.drop_column('animal', 'price')
    op.drop_table('post')
    # ### end Alembic commands ###
