"""empty message

Revision ID: 80728f25cd40
Revises: 6140e02841a1
Create Date: 2022-05-27 00:13:01.065597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80728f25cd40'
down_revision = '6140e02841a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('species', sa.String(length=50), nullable=False))
    op.add_column('animal', sa.Column('latin_name', sa.String(length=255), nullable=True))
    op.add_column('animal', sa.Column('size_cm', sa.Integer(), nullable=True))
    op.add_column('animal', sa.Column('diet', sa.String(length=255), nullable=True))
    op.add_column('animal', sa.Column('lifespan', sa.String(length=255), nullable=True))
    op.alter_column('animal', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'animal', ['species'])
    op.drop_column('animal', 'name')
    op.add_column('user', sa.Column('bio', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bio')
    op.add_column('animal', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'animal', type_='unique')
    op.alter_column('animal', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('animal', 'lifespan')
    op.drop_column('animal', 'diet')
    op.drop_column('animal', 'size_cm')
    op.drop_column('animal', 'latin_name')
    op.drop_column('animal', 'species')
    # ### end Alembic commands ###
